import json

es_translations = {
    "overview": "Resumen",
    "invoices": "Facturas",
    "orders": "Órdenes",
    "subscriptions": "Suscripciones",
    "payment_methods": "Métodos de Pago",
    "financial_center": "Centro Financiero",
    "secure_billing_management": "Gestión segura de facturación",
    "total_revenue": "Ingresos Totales",
    "vs_last_month": "vs. mes anterior",
    "active_subscriptions": "Suscripciones Activas",
    "pending_refunds": "Reembolsos Pendientes",
    "mrr_title": "Ingresos Recurrentes",
    "recent_activity": "Actividad Reciente",
    "view_all": "Ver Todo",
    "products_assets": "Productos y Activos",
    "subscription_plans": "Planes de Suscripción",
    "master_repository": "Repositorio Maestro",
    "critical_failures": "Fallos Críticos",
    "failed_payments": "Pagos Fallidos",
    "no_alerts_require_intervention": "No hay alertas que requieran intervención",
    "add_method": "Agregar Método",
    "add_payment_method": "Agregar Método de Pago",
    "add_payment_method_desc": "Agrega un nuevo método de pago a tu cuenta",
    "card_number": "Número de Tarjeta",
    "cardholder_name": "Nombre del Titular",
    "clear_queue": "Limpiar Cola",
    "close": "Cerrar",
    "confirm": "Confirmar",
    "count_invoices": "Total de Facturas",
    "create_plan": "Crear Plan",
    "create_product": "Crear Producto",
    "current_status": "Estado Actual",
    "customer": "Cliente",
    "customer_view": "Vista del Cliente",
    "cvv": "CVV",
    "date": "Fecha",
    "decline": "Rechazar",
    "delete": "Eliminar",
    "delete_forever": "Eliminar Permanentemente",
    "delete_order": "Eliminar Orden",
    "delete_order_warning": "Esta acción eliminará la orden permanentemente",
    "description": "Descripción",
    "digital_product": "Producto Digital",
    "dismiss": "Descartar",
    "download_invoice": "Descargar Factura",
    "download_invoices": "Descargar Facturas",
    "edit_order": "Editar Orden",
    "edit_payment_method": "Editar Método de Pago",
    "edit_payment_method_desc": "Actualiza los datos de tu método de pago",
    "email": "Correo",
    "encrypted_secure": "Cifrado y Seguro",
    "eom_projection": "Proyección Fin de Mes",
    "financial": "Financiero",
    "free": "Gratis",
    "goal": "Objetivo",
    "invoice_download_error": "Error al descargar la factura",
    "invoice_header": "Encabezado de Factura",
    "invoice_history": "Historial de Facturas",
    "invoice_marked_paid": "Factura marcada como pagada",
    "invoice_voided": "Factura anulada",
    "irreversible_action": "Esta acción es irreversible",
    "licenses": "Licencias",
    "live": "En Vivo",
    "load_error": "Error al cargar",
    "manage": "Gestionar",
    "mark_paid_failed": "Error al marcar como pagada",
    "month": "Mes",
    "monthly": "Mensual",
    "no_billing_history": "Sin historial de facturación",
    "no_events_recorded": "Sin eventos registrados",
    "no_global_products_found": "No se encontraron productos globales",
    "no_invoices": "Sin facturas",
    "no_payment_methods": "Sin métodos de pago",
    "no_plan": "Sin Plan",
    "no_plans_found": "No se encontraron planes",
    "organization": "Organización",
    "owners_only": "Solo Propietarios",
    "paid": "Pagado",
    "payment": "Pago",
    "payment_cancelled": "Pago Cancelado",
    "payment_method": "Método de Pago",
    "paypal_gateway": "Pasarela PayPal",
    "per_month": "por mes",
    "plan_active_shortly": "El plan se activará en breve",
    "plan_name": "Nombre del Plan",
    "plan_now_active": "Plan ahora activo",
    "processing": "Procesando",
    "product": "Producto",
    "product_name": "Nombre del Producto",
    "purchase_pending": "Compra Pendiente",
    "purchase_recorded": "Compra Registrada",
    "queue_clear": "Cola Limpia",
    "refund_order": "Reembolsar Orden",
    "refund_reason_label": "Motivo del Reembolso",
    "refund_reason_placeholder": "Describe el motivo del reembolso...",
    "refund_undone_warning": "Esta acción no se puede deshacer",
    "refunds": "Reembolsos",
    "requests_requiring_attention": "Solicitudes que requieren atención",
    "save_changes": "Guardar Cambios",
    "save_method": "Guardar Método",
    "session_id": "ID de Sesión",
    "showing_invoices": "Mostrando facturas",
    "showing_of_invoices": "Mostrando de facturas",
    "status": "Estado",
    "stripe_gateway": "Pasarela Stripe",
    "subscription_activated": "Suscripción Activada",
    "subscription_management": "Gestión de Suscripciones",
    "subscription_unchanged": "Suscripción sin cambios",
    "success": "Éxito",
    "syncing_alert_data": "Sincronizando datos de alertas",
    "tab": "Pestaña",
    "type_label": "Tipo",
    "updating_subscription": "Actualizando suscripción",
    "upgrade": "Actualizar",
    "user": "Usuario",
    "verifying_purchase": "Verificando compra",
    "view_details": "Ver Detalles",
    "view_transaction": "Ver Transacción",
    "void_failed": "Error al anular",
    "year": "Año",
    "yearly": "Anual",
    "zip": "Código Postal",
    "delivery_email": "Correo de Entrega",
    "downloading_invoice_for": "Descargando factura para",
    "event_cancelled": "Cancelado",
    "event_completed": "Completado",
    "event_created": "Creado",
    "event_paid": "Pagado",
    "event_refunded": "Reembolsado",
    "last_edit": "Última Edición",
    "license_key": "Clave de Licencia",
    "refund": "Reembolso",
    "save": "Guardar",
    "total_paid": "Total Pagado",
    "update_status": "Actualizar Estado",
    "no_active_plans": "Sin planes activos",
    "no_plans_available": "No hay planes disponibles",
    "select_plan": "Seleccionar plan",
    "internal_notes": "Notas Internas",
    "billing_cycle": "Ciclo de Facturación",
    "notes": "Notas",
    "subscription_plan": "Plan de Suscripción",
    "cancel": "Cancelar",
}

with open("src/messages/es.json", "r", encoding="utf-8") as f:
    data = json.load(f)

for k, v in es_translations.items():
    data["billing"][k] = v

with open("src/messages/es.json", "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
    f.write("\n")

print(f"Updated {len(es_translations)} billing keys in es.json")
